In [1]:
import pandas as pd

/tmp/ipykernel_8590/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# read tsv file
df = pd.read_csv('partial_raw.tsv', sep='\t', 
                 names=['sequence_id', 'task_id', 'label', 'events', 'demand_type'], 
                #  dtype={'sequence_id': int, 'task_id': int, 'label': int, 'events': str, 'demand_type': int}
                 )

In [10]:
df.head()

,sequence_id,task_id,label,events,demand_type
0,1,1,0,24 21 36 42 26 53 74 18 13 69 4 30 67 52 33 87...,0.0
1,2,1,0,114 94 96 93 103 102 109 97 97 105 107 101 108...,0.0
2,3,1,0,125 127 123 120 126 121 119 124 124 124 128 11...,0.0
3,4,1,0,139 134 132 165 146 159 178 169 172 154 157 17...,0.0
4,5,1,0,193 202 193 193 186 187 197 210 185 199 189 18...,0.0

In [11]:
# check for missing values
print(df.isnull().sum())

sequence_id    0
task_id        0
label          0
events         0
demand_type    1
dtype: int64

In [12]:
df['demand_type'].value_counts()

demand_type
0.0    1263
Name: count, dtype: int64

In [13]:
df.fillna(float(0), inplace=True)

In [14]:
print(df.isnull().sum())

sequence_id    0
task_id        0
label          0
events         0
demand_type    0
dtype: int64

In [15]:
# check dtype of each column
print(df.dtypes)

sequence_id      int64
task_id          int64
label            int64
events          object
demand_type    float64
dtype: object

In [16]:
# transform demand_type to int
df['demand_type'] = df['demand_type'].astype(int)

In [17]:
print(df.dtypes)

sequence_id     int64
task_id         int64
label           int64
events         object
demand_type     int64
dtype: object

In [18]:
df.events.iloc[0]

'24 21 36 42 26 53 74 18 13 69 4 30 67 52 33 87 78 82 16 78 88 23 86 56 84 35 45 12 59 77 89 80 75 20 15 44 11 60 63 3 17 40 51 29 76 47 55 14 66 37 27 46 34 10 19 83 64 22 49 32 57 48 39 8 25 1 85 50 43 7 6 90 61 26 54 26 54 53 74 58 28 72 5 81 62 38 31 2 71 65 73 79 56 41 91 68 9 70'

In [19]:
# transform events to list of integers
df['events'] = df['events'].apply(lambda x: [int(i) for i in x.split()])
df.head()

,sequence_id,task_id,label,events,demand_type
0,1,1,0,"[24, 21, 36, 42, 26, 53, 74, 18, 13, 69, 4, 30...",0
1,2,1,0,"[114, 94, 96, 93, 103, 102, 109, 97, 97, 105, ...",0
2,3,1,0,"[125, 127, 123, 120, 126, 121, 119, 124, 124, ...",0
3,4,1,0,"[139, 134, 132, 165, 146, 159, 178, 169, 172, ...",0
4,5,1,0,"[193, 202, 193, 193, 186, 187, 197, 210, 185, ...",0

In [20]:
# reverse the order of events
df['events'] = df['events'].apply(lambda x: x[::-1])
df.head()

,sequence_id,task_id,label,events,demand_type
0,1,1,0,"[70, 9, 68, 91, 41, 56, 79, 73, 65, 71, 2, 31,...",0
1,2,1,0,"[117, 95, 115, 99, 111, 113, 100, 110, 98, 106...",0
2,3,1,0,"[122, 118, 128, 124, 124, 124, 119, 121, 126, ...",0
3,4,1,0,"[175, 173, 155, 160, 142, 148, 162, 166, 161, ...",0
4,5,1,0,"[190, 188, 205, 209, 206, 192, 195, 214, 207, ...",0

In [21]:
df.to_csv('partial_raw.csv', index=False)

In [19]:
df = pd.read_csv('partial_raw.csv')
df.head()

,sequence_id,task_id,label,events,demand_type
0,1,1,0,"[70, 9, 68, 91, 41, 56, 79, 73, 65, 71, 2, 31,...",0
1,2,1,0,"[117, 95, 115, 99, 111, 113, 100, 110, 98, 106...",0
2,3,1,0,"[122, 118, 128, 124, 124, 124, 119, 121, 126, ...",0
3,4,1,0,"[175, 173, 155, 160, 142, 148, 162, 166, 161, ...",0
4,5,1,0,"[190, 188, 205, 209, 206, 192, 195, 214, 207, ...",0

In [21]:
print(eval(df.events.iloc[0]))

[70, 9, 68, 91, 41, 56, 79, 73, 65, 71, 2, 31, 38, 62, 81, 5, 72, 28, 58, 74, 53, 54, 26, 54, 26, 61, 90, 6, 7, 43, 50, 85, 1, 25, 8, 39, 48, 57, 32, 49, 22, 64, 83, 19, 10, 34, 46, 27, 37, 66, 14, 55, 47, 76, 29, 51, 40, 17, 3, 63, 60, 11, 44, 15, 20, 75, 80, 89, 77, 59, 12, 45, 35, 84, 56, 86, 23, 88, 78, 16, 82, 78, 87, 33, 52, 67, 30, 4, 69, 13, 18, 74, 53, 26, 42, 36, 21, 24]

In [4]:
# reorder the columns
df = df[['sequence_id', 'events', 'label', 'task_id', 'demand_type']]

In [5]:
# rename columns
df.rename(columns={'sequence_id': 'seq_id', 
                   'events': 'event_id', 
                   'label': 'action_weights', # 'is_relevant'
                   'task_id': 'task_id', 
                   'demand_type': 'demand_type'}, inplace=True)

In [6]:
df.head()

,seq_id,event_id,action_weights,task_id,demand_type
0,1,"[70, 9, 68, 91, 41, 56, 79, 73, 65, 71, 2, 31,...",0,1,0
1,2,"[117, 95, 115, 99, 111, 113, 100, 110, 98, 106...",0,1,0
2,3,"[122, 118, 128, 124, 124, 124, 119, 121, 126, ...",0,1,0
3,4,"[175, 173, 155, 160, 142, 148, 162, 166, 161, ...",0,1,0
4,5,"[190, 188, 205, 209, 206, 192, 195, 214, 207, ...",0,1,0

In [46]:
df.to_csv('processed_seqs_partial.csv', index=False)

In [7]:
import numpy as np
from datetime import datetime, timedelta

# 时间戳生成函数集合

# 方案1: 递增时间戳（推荐）
def generate_incremental_timestamps(sequence_length, start_time=1, interval=1):
    return list(range(start_time, start_time + sequence_length * interval, interval))

# 方案2: 全部设为1（最简单）所有位置都使用相同的时间戳
def generate_constant_timestamps(sequence_length, timestamp=1):
    return [timestamp] * sequence_length

# 方案3: 基于位置的相对时间（模拟真实时间间隔）
def generate_position_based_timestamps(sequence_length, base_interval=3600):
    timestamps = [1]  # 起始时间戳
    current_time = 1
    
    for i in range(1, sequence_length):
        # 添加一些随机性，模拟真实的不等间隔
        interval = base_interval + np.random.randint(-base_interval//2, base_interval//2)
        current_time += max(interval, 1)  # 确保时间戳递增
        timestamps.append(current_time)
    
    return timestamps

# 方案4: Unix时间戳风格（2025年4月16-22日）
def generate_custom_unix_timestamps(sequence_length):
    """
    在2025年4月16-22日范围内生成Unix时间戳
    """
    # 设定时间范围
    start_date = datetime(2025, 4, 16, 0, 0, 0)  # 2025年4月16日 00:00:00
    end_date = datetime(2025, 4, 22, 23, 59, 59)  # 2025年4月22日 23:59:59
    
    start_timestamp = int(start_date.timestamp())
    end_timestamp = int(end_date.timestamp())
    
    if sequence_length == 1:
        return [start_timestamp]
    
    # 计算可用的总时间范围
    total_time_span = end_timestamp - start_timestamp
    max_interval = total_time_span // (sequence_length - 1)
    
    # 使用指数分布，但限制最大值
    scale = min(3600, max_interval // 2)  # 平均1小时或更短
    intervals = np.random.exponential(scale, sequence_length-1)
    
    # 限制间隔，确保不超出时间范围
    intervals = np.minimum(intervals, max_interval * 0.8)
    
    # 如果总间隔超出范围，按比例缩放
    total_intervals = np.sum(intervals)
    if total_intervals > total_time_span * 0.9:
        scale_factor = (total_time_span * 0.9) / total_intervals
        intervals = intervals * scale_factor
    
    # 生成时间戳序列
    timestamps = [start_timestamp]
    current_time = start_timestamp
    
    for interval in intervals:
        current_time += int(interval)
        current_time = min(current_time, end_timestamp)  # 确保不超过结束时间
        timestamps.append(current_time)
    
    return timestamps

# 测试各种方案
test_seq_length = 10
print("=== 时间戳方案对比 ===")
print("序列长度:", test_seq_length)
print("\n各种时间戳方案:")
print("方案1 (incremental):", generate_incremental_timestamps(test_seq_length))
print("方案2 (constant):", generate_constant_timestamps(test_seq_length))
print("方案3 (position-based):", generate_position_based_timestamps(test_seq_length))

# Unix风格示例
unix_example = generate_custom_unix_timestamps(test_seq_length)
print("方案4 (Unix):", unix_example)
print("对应时间:", [datetime.fromtimestamp(ts).strftime('%m-%d %H:%M') for ts in unix_example[:3]], "...")

=== 时间戳方案对比 ===
序列长度: 10

各种时间戳方案:
方案1 (incremental): [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
方案2 (constant): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
方案3 (position-based): [1, 4013, 8565, 10745, 16073, 18819, 20810, 23333, 28557, 33335]
方案4 (Unix): [1744761600, 1744763106, 1744768665, 1744769153, 1744779387, 1744789208, 1744792759, 1744800422, 1744802820, 1744805710]
对应时间: ['04-16 00:00', '04-16 00:25', '04-16 01:57'] ...

In [22]:
import pandas as pd
df = pd.read_csv('processed_seqs_partial.csv')

In [23]:
df.head()

,seq_id,event_id,action_weights,task_id,demand_type
0,1,"[70, 9, 68, 91, 41, 56, 79, 73, 65, 71, 2, 31,...",0,1,0
1,2,"[117, 95, 115, 99, 111, 113, 100, 110, 98, 106...",0,1,0
2,3,"[122, 118, 128, 124, 124, 124, 119, 121, 126, ...",0,1,0
3,4,"[175, 173, 155, 160, 142, 148, 162, 166, 161, ...",0,1,0
4,5,"[190, 188, 205, 209, 206, 192, 195, 214, 207, ...",0,1,0

In [24]:
# 为数据集添加时间戳的通用函数

def add_timestamps_to_sequence(df, method='custom_unix'):
    timestamps_list = []
    
    # 根据不同方法生成时间戳
    print(f"\n=== Generating {method} timestamps ===")
    for i, row in df.iterrows():
        seq_length = len(eval(row['event_id']))
        
        if method == 'incremental':
            timestamps = generate_incremental_timestamps(seq_length)
        elif method == 'constant':
            timestamps = generate_constant_timestamps(seq_length)
        elif method == 'position_based':
            timestamps = generate_position_based_timestamps(seq_length)
        elif method == 'custom_unix':
            timestamps = generate_custom_unix_timestamps(seq_length)
        else:
            raise ValueError(f"Unsupported method: {method}")
        
        timestamps_list.append(timestamps)
        
        
    return timestamps_list


# 推荐方案：定制Unix时间戳（2025年4月16-22日）
df['timestamps_unix'] = add_timestamps_to_sequence(df, 'custom_unix')

# 也生成递增时间戳作为备选
df['timestamps_constant'] = add_timestamps_to_sequence(df, 'constant')

print(f"\n=== Timestamp 添加完成 ===")
print(f"共处理 {len(df)} 个序列")

=== Generating custom_unix timestamps ===

=== Generating constant timestamps ===

=== Timestamp 添加完成 ===
共处理 1264 个序列

In [35]:
# generate action weights for each event_id
def generate_action_weights(df, method='all_0'):
    action_weights_list = []
    
    for i, row in df.iterrows():
        seq_length = len(eval(row['event_id'])) - 1
        target_label = row['action_weights']

        if method == 'all_0':
            action_weights = [0] * seq_length
        elif method == 'all_1':
            action_weights = [1] * seq_length
        else:
            raise ValueError(f"Unsupported method: {method}")
        action_weights.append(target_label)
        action_weights_list.append(action_weights)
    
    return action_weights_list

In [37]:
df['action_weights'] = generate_action_weights(df, 'all_0')

In [40]:
df = df[['seq_id', 'event_id', 'action_weights', 'timestamps_unix', 'timestamps_constant', 'task_id', 'demand_type']]

In [43]:
df.to_csv('processed_seqs_time_partial.csv', index=False)

In [38]:
df.head(2)

,seq_id,event_id,action_weights,task_id,demand_type,timestamps_unix,timestamps_constant
0,1,"[70, 9, 68, 91, 41, 56, 79, 73, 65, 71, 2, 31,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0,"[1744761600, 1744762994, 1744763053, 174476370...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,2,"[117, 95, 115, 99, 111, 113, 100, 110, 98, 106...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0,"[1744761600, 1744763189, 1744766109, 174477399...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [14]:
df.action_weights.value_counts()

action_weights
0    970
1    294
Name: count, dtype: int64

In [ ]:
# 简化版本 - 直接使用您的处理逻辑
def process_partial_raw_simple(input_file='partial_raw.tsv', output_file='processed_seqs_time_partial.csv'):
    """
    简化版本的数据处理函数，直接复用您现有的逻辑
    """
    import pandas as pd
    import numpy as np
    from datetime import datetime
    
    # 读取数据
    df = pd.read_csv(input_file, sep='\t', 
                     names=['sequence_id', 'task_id', 'label', 'events', 'demand_type'])
    
    # 处理缺失值
    df.dropna(inplace=True)
    
    # 转换数据类型
    df['demand_type'] = df['demand_type'].astype(int)
    
    # 处理events - 转换为整数列表并反转
    df['events'] = df['events'].apply(lambda x: [int(i) for i in x.split()][::-1])
    
    # 重新排列和重命名列
    df = df[['sequence_id', 'events', 'label', 'task_id', 'demand_type']]
    df.rename(columns={'sequence_id': 'seq_id', 
                       'events': 'event_id', 
                       'label': 'action_weights',
                       'task_id': 'task_id', 
                       'demand_type': 'demand_type'}, inplace=True)
    
    # 生成Unix时间戳
    def generate_custom_unix_timestamps(sequence_length):
        start_date = datetime(2025, 4, 16, 0, 0, 0)
        end_date = datetime(2025, 4, 22, 23, 59, 59)
        start_timestamp = int(start_date.timestamp())
        end_timestamp = int(end_date.timestamp())
        
        if sequence_length == 1:
            return [start_timestamp]
        
        total_time_span = end_timestamp - start_timestamp
        max_interval = total_time_span // (sequence_length - 1)
        scale = min(3600, max_interval // 2)
        intervals = np.random.exponential(scale, sequence_length-1)
        intervals = np.minimum(intervals, max_interval * 0.8)
        
        total_intervals = np.sum(intervals)
        if total_intervals > total_time_span * 0.9:
            scale_factor = (total_time_span * 0.9) / total_intervals
            intervals = intervals * scale_factor
        
        timestamps = [start_timestamp]
        current_time = start_timestamp
        for interval in intervals:
            current_time += int(interval)
            current_time = min(current_time, end_timestamp)
            timestamps.append(current_time)
        return timestamps
    
    # 生成时间戳
    timestamps_list = []
    for i, row in df.iterrows():
        seq_length = len(row['event_id'])
        timestamps = generate_custom_unix_timestamps(seq_length)
        timestamps_list.append(timestamps)
    
    df['timestamps_unix'] = timestamps_list
    
    # 生成常数时间戳作为备选
    df['timestamps_constant'] = df['event_id'].apply(lambda x: [1] * len(x))
    
    # 生成动作权重
    action_weights_list = []
    for i, row in df.iterrows():
        seq_length = len(row['event_id']) - 1
        target_label = row['action_weights']
        action_weights = [0] * seq_length + [target_label]
        action_weights_list.append(action_weights)
    
    df['action_weights'] = action_weights_list
    
    # 最终列排序
    df = df[['seq_id', 'event_id', 'action_weights', 'timestamps_unix', 'timestamps_constant', 'task_id', 'demand_type']]
    
    # 保存文件
    df.to_csv(output_file, index=False)
    
    return df

# 使用示例
# result_df = process_partial_raw_simple()
# print(result_df.head(2))

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

def process_raw_data_to_sequences(input_file='partial_raw.tsv', output_file='processed_seqs_time_partial.csv', 
                                  timestamp_method='custom_unix', action_weight_method='all_0'):
    """
    将原始TSV文件处理成用于推荐系统的序列数据
    
    Parameters:
    -----------
    input_file : str
        输入的TSV文件路径
    output_file : str
        输出的CSV文件路径
    timestamp_method : str
        时间戳生成方法: 'incremental', 'constant', 'position_based', 'custom_unix'
    action_weight_method : str
        动作权重生成方法: 'all_0', 'all_1'
    
    Returns:
    --------
    pd.DataFrame
        处理后的数据框
    """
    
    # 时间戳生成函数
    def generate_incremental_timestamps(sequence_length, start_time=1, interval=1):
        return list(range(start_time, start_time + sequence_length * interval, interval))

    def generate_constant_timestamps(sequence_length, timestamp=1):
        return [timestamp] * sequence_length

    def generate_position_based_timestamps(sequence_length, base_interval=3600):
        timestamps = [1]
        current_time = 1
        
        for i in range(1, sequence_length):
            interval = base_interval + np.random.randint(-base_interval//2, base_interval//2)
            current_time += max(interval, 1)
            timestamps.append(current_time)
        
        return timestamps

    def generate_custom_unix_timestamps(sequence_length):
        """在2025年4月16-22日范围内生成Unix时间戳"""
        start_date = datetime(2025, 4, 16, 0, 0, 0)
        end_date = datetime(2025, 4, 22, 23, 59, 59)
        
        start_timestamp = int(start_date.timestamp())
        end_timestamp = int(end_date.timestamp())
        
        if sequence_length == 1:
            return [start_timestamp]
        
        total_time_span = end_timestamp - start_timestamp
        max_interval = total_time_span // (sequence_length - 1)
        
        scale = min(3600, max_interval // 2)
        intervals = np.random.exponential(scale, sequence_length-1)
        intervals = np.minimum(intervals, max_interval * 0.8)
        
        total_intervals = np.sum(intervals)
        if total_intervals > total_time_span * 0.9:
            scale_factor = (total_time_span * 0.9) / total_intervals
            intervals = intervals * scale_factor
        
        timestamps = [start_timestamp]
        current_time = start_timestamp
        
        for interval in intervals:
            current_time += int(interval)
            current_time = min(current_time, end_timestamp)
            timestamps.append(current_time)
        
        return timestamps
    
    def generate_timestamps(seq_length, method):
        """根据方法生成时间戳"""
        if method == 'incremental':
            return generate_incremental_timestamps(seq_length)
        elif method == 'constant':
            return generate_constant_timestamps(seq_length)
        elif method == 'position_based':
            return generate_position_based_timestamps(seq_length)
        elif method == 'custom_unix':
            return generate_custom_unix_timestamps(seq_length)
        else:
            raise ValueError(f"Unsupported timestamp method: {method}")
    
    def generate_action_weights(event_list, target_label, method):
        """生成动作权重"""
        seq_length = len(event_list) - 1
        
        if method == 'all_0':
            action_weights = [0] * seq_length
        elif method == 'all_1':
            action_weights = [1] * seq_length
        else:
            raise ValueError(f"Unsupported action weight method: {method}")
        
        action_weights.append(target_label)
        return action_weights
    
    print(f"开始处理文件: {input_file}")
    
    # 1. 读取TSV文件
    df = pd.read_csv(input_file, sep='\t', 
                     names=['sequence_id', 'task_id', 'label', 'events', 'demand_type'])
    
    print(f"原始数据形状: {df.shape}")
    print(f"缺失值统计:\n{df.isnull().sum()}")
    
    # 2. 处理缺失值
    df.fillna(float(0), inplace=True)
    
    # 3. 转换数据类型
    df['demand_type'] = df['demand_type'].astype(int)
    
    # 4. 处理events列 - 转换为整数列表并反转
    df['events'] = df['events'].apply(lambda x: [int(i) for i in x.split()][::-1])
    
    # 5. 重新排列和重命名列
    df = df[['sequence_id', 'events', 'label', 'task_id', 'demand_type']]
    df.rename(columns={
        'sequence_id': 'seq_id', 
        'events': 'event_id', 
        'label': 'action_weights',
        'task_id': 'task_id', 
        'demand_type': 'demand_type'
    }, inplace=True)
    
    # 6. 生成时间戳
    print(f"生成时间戳 (方法: {timestamp_method})")
    timestamps_list = []
    action_weights_list = []
    
    for i, row in df.iterrows():
        event_list = row['event_id']
        seq_length = len(event_list)
        target_label = row['action_weights']
        
        # 生成时间戳
        timestamps = generate_timestamps(seq_length, timestamp_method)
        timestamps_list.append(timestamps)
        
        # 生成动作权重
        action_weights = generate_action_weights(event_list, target_label, action_weight_method)
        action_weights_list.append(action_weights)
    
    # 7. 更新DataFrame
    df['timestamps'] = timestamps_list
    df['action_weights'] = action_weights_list
    
    # 8. 最终列排序
    df = df[['seq_id', 'event_id', 'action_weights', 'timestamps', 'task_id', 'demand_type']]
    
    # 9. 保存结果
    df.to_csv(output_file, index=False)
    
    print(f"处理完成!")
    print(f"最终数据形状: {df.shape}")
    print(f"输出文件: {output_file}")
    
    return df

# 使用示例
if __name__ == "__main__":
    # 处理数据
    processed_df = process_raw_data_to_sequences(
        input_file='partial_raw.tsv',
        output_file='processed_seqs_time_partial.csv',
        timestamp_method='custom_unix',
        action_weight_method='all_0'
    )
    
    # 显示前几行结果
    print("\n前5行数据:")
    print(processed_df.head())
    
    print(f"\n动作权重分布:")
    print(processed_df['action_weights'].apply(lambda x: x[-1]).value_counts())