In [1]:
import pandas as pd

/tmp/ipykernel_21476/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv('processed_seqs.csv')
df.head(2)

,user_id,video_id,time_ms,action_weights,play_time_ms,duration_ms,user_active_degree,is_lowactive_period,is_live_streamer,is_video_author,...,onehot_feat8,onehot_feat9,onehot_feat10,onehot_feat11,onehot_feat12,onehot_feat13,onehot_feat14,onehot_feat15,onehot_feat16,onehot_feat17
0,0,"[4354972, 1329429, 346081, 2058916, 2528540, 1...","[1649467982289, 1649467982289, 1649467982289, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 5332, 0, 0, 0, 0, 0, 0, 791, 2683...","[70100, 51422, 11696, 66433, 11450, 22016, 426...",1,0,1,1,...,135,6,3,0,0.0,1.0,0.0,0.0,0.0,0.0
1,1,"[416357, 4165882, 3837345, 2776381, 4362455, 1...","[1649407952855, 1649407952855, 1649407952855, ...","[65, 128, 65, 65, 0, 65, 65, 0, 0, 65, 0, 65, ...","[101551, 6282, 8367, 21072, 3173, 68324, 12656...","[481966, 7060, 5866, 8100, 14066, 67283, 16040...",1,0,-124,1,...,283,6,2,2,1.0,0.0,1.0,0.0,0.0,0.0

In [8]:
# map action_weights to binary values: if action_weights > 0, set to 1; if action_weights = 0, set to 0
def action_weights_to_binary(action_weights_str):
    action_weights = eval(action_weights_str)
    action_weights = [1 if weight > 0 else 0 for weight in action_weights]
    return str(action_weights)

df['action_weights'] = df['action_weights'].apply(action_weights_to_binary)

df.head(2)

,user_id,video_id,time_ms,action_weights,play_time_ms,duration_ms,user_active_degree,is_lowactive_period,is_live_streamer,is_video_author,...,onehot_feat8,onehot_feat9,onehot_feat10,onehot_feat11,onehot_feat12,onehot_feat13,onehot_feat14,onehot_feat15,onehot_feat16,onehot_feat17
0,0,"[4354972, 1329429, 346081, 2058916, 2528540, 1...","[1649467982289, 1649467982289, 1649467982289, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 5332, 0, 0, 0, 0, 0, 0, 791, 2683...","[70100, 51422, 11696, 66433, 11450, 22016, 426...",1,0,1,1,...,135,6,3,0,0.0,1.0,0.0,0.0,0.0,0.0
1,1,"[416357, 4165882, 3837345, 2776381, 4362455, 1...","[1649407952855, 1649407952855, 1649407952855, ...","[1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, ...","[101551, 6282, 8367, 21072, 3173, 68324, 12656...","[481966, 7060, 5866, 8100, 14066, 67283, 16040...",1,0,-124,1,...,283,6,2,2,1.0,0.0,1.0,0.0,0.0,0.0

In [9]:
df.to_csv('processed_seqs_binary.csv', index=False)

In [4]:
# read the first row of df['video_id']
len(eval(df['video_id'].iloc[0]))

15538

In [8]:
len(eval(df['time_ms'].iloc[0]))

15538

In [11]:
len(eval(df['duration_ms'].iloc[0]))

15538

In [6]:
df.columns

Index(['user_id', 'video_id', 'time_ms', 'action_weights', 'play_time_ms',
       'duration_ms', 'user_active_degree', 'is_lowactive_period',
       'is_live_streamer', 'is_video_author', 'follow_user_num',
       'follow_user_num_range', 'fans_user_num', 'fans_user_num_range',
       'friend_user_num', 'friend_user_num_range', 'register_days',
       'register_days_range', 'onehot_feat0', 'onehot_feat1', 'onehot_feat2',
       'onehot_feat3', 'onehot_feat4', 'onehot_feat5', 'onehot_feat6',
       'onehot_feat7', 'onehot_feat8', 'onehot_feat9', 'onehot_feat10',
       'onehot_feat11', 'onehot_feat12', 'onehot_feat13', 'onehot_feat14',
       'onehot_feat15', 'onehot_feat16', 'onehot_feat17'],
      dtype='object')